### ISSUE TITLE
Install Error on Linux

### ISSUE THREAD

**Issue by pine3825** [Fuhua-Chen/ReSpeaker-Microphone-Array-HID-tool#1]
Dear
I try the procedures below.
But there are many errors.
Could you have any idea?
-----------------------------------
git clone https://github.com/Fuhua-Chen/ReSpeaker-Microphone-Array-HID-tool
cd ReSpeaker-Microphone-Array-HID-tool
sudo apt install nodejs-legacy
sudo apt install npm
sh ./install_linux.sh
-------------------------------------
jaehoon@jaehoon-UP:~/Workspace/ReSpeaker/ReSpeaker-Microphone-Array-HID-tool$ sh ./install_linux.sh

> node-hid@0.5.2 install /home/jaehoon/Workspace/ReSpeaker/ReSpeaker-Microphone-Array-HID-tool/node-hid
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/node-hid/node-hid/releases/download/0.5.2/HID-v0.5.2-node-v46-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node-hid@0.5.2 and node@4.2.6 (node-v46 ABI) (falling back to source compile with node-gyp) 
make: Entering directory '/home/jaehoon/Workspace/ReSpeaker/ReSpeaker-Microphone-Array-HID-tool/node-hid/build'
make: *** No rule to make target 'Release/obj.target/hidapi/hidapi/libusb/hid.o', needed by 'Release/obj.target/hidapi.a'.  Stop.
make: Leaving directory '/home/jaehoon/Workspace/ReSpeaker/ReSpeaker-Microphone-Array-HID-tool/node-hid/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)

======================
I run the command again.
-------------------------------------
└─┬ rimraf@2.5.4 
  └─┬ glob@7.1.2 
    ├── fs.realpath@1.0.0 
    ├── inflight@1.0.6 
    ├─┬ minimatch@3.0.4 
    │ └─┬ brace-expansion@1.1.8 
    │   ├── balanced-match@1.0.0 
    │   └── concat-map@0.0.1 
    ├── once@1.4.0 
    └── path-is-absolute@1.0.1 

Press any key to continue.install_linux.sh: 7: read: arg count
jaehoon@jaehoon-UP:~/Workspace/ReSpeaker/ReSpeaker-Microphone-Array-HID-tool$

**Comment by pine3825** [comment]
I fixed the problems as below procedure.
-----------------------
https://github.com/node-hid/node-hid
===========================================
To build node-hid for development:

    check out a copy of this repo
    change into its directory
    update the submodules
    build the node package

For example:

git clone https://github.com/node-hid/node-hid.git
cd node-hid                                        # must change into node-hid directory
npm run prepublish                                 # get the needed hidapi submodule
npm install --build-from-source                    # rebuilds the module with C code
node ./src/show-devices.js

=========================
jaehoon@jaehoon-UP:~/Workspace/ReSpeaker/ReSpeaker-Microphone-Array-HID-tool/node-hid$ ls
appveyor.yml  build   nodehid.js    nwjs-old-install.sh  Publishing.md  src
binding.gyp   hidapi  node_modules  package.json         README.md
