### ISSUE TITLE
Errors installing on Ubuntu 14.04

### ISSUE THREAD

**Issue by jhoelzl** [Fuhua-Chen/ReSpeaker-Microphone-Array-HID-tool#2]
Hello,

i tried to install like this:

*  `git clone https://github.com/Fuhua-Chen/ReSpeaker-Microphone-Array-HID-tool`
*   `cd ReSpeaker-Microphone-Array-HID-tool`
*   `sh ./install_linux.sh` returns a lot of errors, so i tried  `sudo sh ./install_linux.sh` which seems to work with some warnings.

When i run `node michid.js set 0 4 0xffffff01` i get the following errors:

> module.js:340
>     throw err;
>           ^
> Error: Cannot find module '/media/user/data/respeaker/ReSpeaker-Microphone-Array-HID-tool/node-hid/build/HID/Release/HID.node'
>     at Function.Module._resolveFilename (module.js:338:15)
>     at Function.Module._load (module.js:280:25)
>     at Module.require (module.js:364:17)
>     at require (module.js:380:17)
>     at Object.<anonymous> (/media/user/data/respeaker/ReSpeaker-Microphone-Array-HID-tool/node-hid/nodehid.js:9:15)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Module.require (module.js:364:17)
> 

It seems that the folder node-hid/build is not generated by the installation. Any suggestions?

Regards,
Josef

**Comment by pine3825** [comment]
I fixed the problems as below procedure.
https://github.com/node-hid/node-hid

To build node-hid for development:

check out a copy of this repo
change into its directory
update the submodules
build the node package

For example:

git clone https://github.com/node-hid/node-hid.git
cd node-hid # must change into node-hid directory
npm run prepublish # get the needed hidapi submodule
npm install --build-from-source # rebuilds the module with C code
node ./src/show-devices.js

=========================
jaehoon@jaehoon-UP:~/Workspace/ReSpeaker/ReSpeaker-Microphone-Array-HID-tool/node-hid$ ls
appveyor.yml build nodehid.js nwjs-old-install.sh Publishing.md src
binding.gyp hidapi node_modules package.json README.md
