### ISSUE TITLE
Command Error

### ISSUE THREAD

**Issue by pine3825** [Fuhua-Chen/ReSpeaker-Microphone-Array-HID-tool#3]
I run the command node michid.js set 0 4 0xffffff01
but there are errors.
Do you have any ideas??
--------------------------------------------------

jaehoon@jaehoon-UP:~/Workspace/ReSpeaker/ReSpeaker-Microphone-Array-HID-tool$ node michid.js set 0 4 0xffffff01
module.js:328
    throw err;
    ^

Error: Cannot find module '/home/jaehoon/Workspace/ReSpeaker/ReSpeaker-Microphone-Array-HID-tool/node-hid/build/HID/Release/HID.node'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/jaehoon/Workspace/ReSpeaker/ReSpeaker-Microphone-Array-HID-tool/node-hid/nodehid.js:9:15)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)

**Comment by pine3825** [comment]
I fixed the problems as below procedure.
https://github.com/node-hid/node-hid

To build node-hid for development:

check out a copy of this repo
change into its directory
update the submodules
build the node package

For example:

git clone https://github.com/node-hid/node-hid.git
cd node-hid # must change into node-hid directory
npm run prepublish # get the needed hidapi submodule
npm install --build-from-source # rebuilds the module with C code
node ./src/show-devices.js

=========================
jaehoon@jaehoon-UP:~/Workspace/ReSpeaker/ReSpeaker-Microphone-Array-HID-tool/node-hid$ ls
appveyor.yml build nodehid.js nwjs-old-install.sh Publishing.md src
binding.gyp hidapi node_modules package.json README.md
