### ISSUE TITLE
 npm update check failed 

### ISSUE THREAD

**Issue by gdpeter8075** [Fuhua-Chen/ReSpeaker-Microphone-Array-HID-tool#5]
- I run the following commend before I run .\install_win.bat

npm install -g node-pre-gyp
npm install -g node-pre-gyp-github
npm install -g rimraf

- after I run .\install_win.bat. My commend window gives me lots of warning:

..\src\HID.cc(67): warning C4290: C++ exception specification ignored except to indicate a function is not __declspec(n
othrow) [C:\Users\Mylaptop\Downloads\ReSpeaker-Microphone-Array-HID-tool\node-hid\build\HID.vcxproj]
..\src\HID.cc(70): warning C4290: C++ exception specification ignored except to indicate a function is not __declspec(n
othrow) [C:\Users\Mylaptop\Downloads\ReSpeaker-Microphone-Array-HID-tool\node-hid\build\HID.vcxproj]
..\src\HID.cc(152): warning C4290: C++ exception specification ignored except to indicate a function is not __declspec(
nothrow) [C:\Users\Mylaptop\Downloads\ReSpeaker-Microphone-Array-HID-tool\node-hid\build\HID.vcxproj]
..\src\HID.cc(163): warning C4290: C++ exception specification ignored except to indicate a function is not __declspec(
nothrow) [C:\Users\Mylaptop\Downloads\ReSpeaker-Microphone-Array-HID-tool\node-hid\build\HID.vcxproj]
..\src\HID.cc(207): warning C4996: 'v8::Function::NewInstance': was declared deprecated [C:\Users\Mylaptop\Downloads\
ReSpeaker-Microphone-Array-HID-tool\node-hid\build\HID.vcxproj]
  c:\users\Mylaptop\.node-gyp\8.9.1\include\node\v8.h(3831): note: see declaration of 'v8::Function::NewInstance'
..\src\HID.cc(398): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc [C:\
Users\Mylaptop\Downloads\ReSpeaker-Microphone-Array-HID-tool\node-hid\build\HID.vcxproj]
..\src\HID.cc(488): warning C4244: 'argument': conversion from 'wchar_t' to 'char', possible loss of data [C:\Users\Mylaptop\Downloads\ReSpeaker-Microphone-Array-HID-tool\node-hid\build\HID.vcxproj]
     Creating library C:\Users\Mylaptop\Downloads\ReSpeaker-Microphone-Array-HID-tool\node-hid\build\Release\HID.lib
  and object C:\Users\Mylaptop\Downloads\ReSpeaker-Microphone-Array-HID-tool\node-hid\build\Release\HID.exp
  Generating code
  Finished generating code
  HID.vcxproj -> C:\Users\Mylaptop\Downloads\ReSpeaker-Microphone-Array-HID-tool\node-hid\build\Release\\HID.node
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> node-hid@0.5.7 prepublish C:\Users\Mylaptop\Downloads\ReSpeaker-Microphone-Array-HID-tool\node-hid
> git submodule update --init

┌─────────────────────────────────────────────────────────────────┐
│                     npm update check failed                     │
│               Try running with sudo or get access               │
│              to the local update config store via               │
│ sudo chown -R $USER:$(id -gn $USER) C:\Users\Mylaptop\.config │
└─────────────────────────────────────────────────────────────────┘

Does any one know what does this error means?

Thanks

**Comment by gdpeter8075** [comment]
I also try to run: node michid.js set 0 4 0xffffff01
but the commend window gives me following massage:

 device.write(tmp);
               ^
Error: Cannot write to HID device
    at Object.set_reg_value (C:\Users\Mylaptop\Downloads\ReSpeaker-Microphone-Array-HID-tool\michid.js:40:16)
    at Object.<anonymous> (C:\Users\Mylaptop\Downloads\ReSpeaker-Microphone-Array-HID-tool\michid.js:150:30)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

Does this means I have some files missing?
